#pragma once

// Aggregates all *Sequential headers
#include "get_version_sequential.h"
#include "serial_abort_read_sequential.h"
#include "serial_abort_write_sequential.h"
#include "serial_clear_buffer_in_sequential.h"
#include "serial_clear_buffer_out_sequential.h"
#include "serial_close_sequential.h"
#include "serial_drain_sequential.h"
#include "serial_get_ports_info_sequential.h"
#include "serial_in_bytes_total_sequential.h"
#include "serial_in_bytes_waiting_sequential.h"
#include "serial_open_sequential.h"
#include "serial_out_bytes_total_sequential.h"
#include "serial_out_bytes_waiting_sequential.h"
#include "serial_read_line_sequential.h"
#include "serial_read_sequential.h"
#include "serial_read_until_sequence_sequential.h"
#include "serial_read_until_sequential.h"
#include "serial_set_error_callback_sequential.h"
#include "serial_set_read_callback_sequential.h"
#include "serial_set_write_callback_sequential.h"
#include "serial_write_sequential.h"
