#pragma once

inline constexpr auto kStatusCodeDescriptors = std::array{
    StatusCodeDescriptor{"General", "Success", StatusCode::kSuccess},
    detail::makeStatusCodeDescriptor(StatusCode::Configuration::kSetBaudrateError),
    detail::makeStatusCodeDescriptor(StatusCode::Configuration::kSetDataBitsError),
    detail::makeStatusCodeDescriptor(StatusCode::Configuration::kSetParityError),
    detail::makeStatusCodeDescriptor(StatusCode::Configuration::kSetStopBitsError),
    detail::makeStatusCodeDescriptor(StatusCode::Configuration::kSetFlowControlError),
    detail::makeStatusCodeDescriptor(StatusCode::Configuration::kSetTimeoutError),
    detail::makeStatusCodeDescriptor(StatusCode::Connection::kNotFoundError),
    detail::makeStatusCodeDescriptor(StatusCode::Connection::kInvalidHandleError),
    detail::makeStatusCodeDescriptor(StatusCode::Connection::kCloseHandleError),
    detail::makeStatusCodeDescriptor(StatusCode::Io::kReadError),
    detail::makeStatusCodeDescriptor(StatusCode::Io::kWriteError),
    detail::makeStatusCodeDescriptor(StatusCode::Io::kAbortReadError),
    detail::makeStatusCodeDescriptor(StatusCode::Io::kAbortWriteError),
    detail::makeStatusCodeDescriptor(StatusCode::Io::kBufferError),
    detail::makeStatusCodeDescriptor(StatusCode::Io::kClearBufferInError),
    detail::makeStatusCodeDescriptor(StatusCode::Io::kClearBufferOutError),
    detail::makeStatusCodeDescriptor(StatusCode::Control::kSetDtrError),
    detail::makeStatusCodeDescriptor(StatusCode::Control::kSetRtsError),
    detail::makeStatusCodeDescriptor(StatusCode::Control::kGetModemStatusError),
    detail::makeStatusCodeDescriptor(StatusCode::Control::kSendBreakError),
    detail::makeStatusCodeDescriptor(StatusCode::Control::kGetStateError),
    detail::makeStatusCodeDescriptor(StatusCode::Control::kSetStateError),
    detail::makeStatusCodeDescriptor(StatusCode::Monitor::kMonitorError),
};
