name: 'Build WASM binary'

on:
  push:
    branches: 
      - 'main'
      
    paths:
      - '.github/workflows/build.yml'

  workflow_dispatch:
    inputs:
      build:
        description: 'Build WASM binary'
        required: true
        default: 'RELEASE'
        type: choice
        options:
          - 'RELEASE'
          - 'PRE_REPEASE'
        

env:
  BUILD_TYPE: 'RELEASE'

jobs:
  build:
    name: 'Build WASM binary'
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Set BUILD_TYPE'
      run: |
        if ([ -n "${{ github.event.inputs.build }}" ]); then
          echo "Using input value: ${{ github.event.inputs.build }}"
          echo "::set-env name=BUILD_TYPE::${{ github.event.inputs.build }}"
        else
          echo "Using default value: ${{ env.BUILD_TYPE }}"
          echo "::set-env name=BUILD_TYPE::${{ env.BUILD_TYPE }}"
        fi
